#开发环境
server:
  port: 80
# oracle
spring:
  datasource:
    druid: #druid监控页面
      stat-view-servlet:
        enabled: true
        loginUsername: admin #配置用户名
        loginPassword: admin #配置密码
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        initial-size: 1
        max-active: 20
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000 #配置获取连接等待超时的时间
        min-evictable-idle-time-millis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        validation-query: select 1 from dual
        pool-prepared-statements: true
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
      primary: wsyy #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource: #支持数据库连接信息加密 ENC(xxxxx) java: CryptoUtils.encrypt(password) 现在暂时不用
        wsyy:
          url: jdbc:oracle:thin:@192.168.100.144:1521:orcl
          username: test
          password: test
          driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: 192.168.100.144
    port: 6379
    password: wsyy #不可纯数字
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 5000 #超时时间必须大于0
  session:
    store-type: redis
  main:
    allow-bean-definition-overriding: true


mybatis-plus:
  type-aliases-package: com.wsyy.*.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

swagger:
  enabled: true

mongodb:
  #是否使用mongoDB上传
  enabled: true

jpush:
  #极光消息推送是否开启
  enabled: true
  prodEnv: false
